plantilla/administrador/urls.py
from django.urls import path, re_path
from django.contrib.auth.views import logout
from administrador.views import (
	LoginAdmin,
	login_admin,
	HomeAdmin,
	SlidersAdmin,
	NewEditViewSlider,
	post_add_edit,
	post_delete_slider,
	ContenidosAdmin,
	NewEditViewContenido,
	post_add_edit_contenido,
	post_delete_contenido
)

app_name = 'manage'

urlpatterns = [
	path('', LoginAdmin.as_view(), name = 'home'),
	path('login', login_admin, name = 'login'),
	path('logout/', logout, {'next_page': '/manage'}, name='logout'),
	path('home/', HomeAdmin.as_view(), name = 'homeadmin'),
	path('slider/', SlidersAdmin.as_view(), name = 'slider'),
	path('slidernewedit/<actiontype>/', NewEditViewSlider.as_view(), name = 'addeditslider'),
	path('slidernewedit/<actiontype>/<id>/', NewEditViewSlider.as_view(), name = 'addeditslider'),
	path('newslider/', post_add_edit, name = 'postnewslider'),
	path('editslider/', post_add_edit, name = 'posteditslider'),
	path('deleteslider/<id>', post_delete_slider, name = 'postdeleteslider'),
	path('contenidos/', ContenidosAdmin.as_view(), name = 'contenidos'),
	path('contenidonewedit/<actiontype>/', NewEditViewContenido.as_view(), name = 'addeditcontenido'),
	path('contenidonewedit/<actiontype>/<id>/', NewEditViewContenido.as_view(), name = 'addeditcontenido'),
	path('newcontenido/', post_add_edit_contenido, name = 'postnewcontenido'),
	path('editcontenido/', post_add_edit_contenido, name = 'posteditcontenido'),
	path('deletecontenido/<id>', post_delete_contenido, name = 'postdeletecontenido')
]

plantilla/plantilla/urls.py
from django.contrib import admin
from filebrowser.sites import site
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
	path('admin-manage/filebrowser/', site.urls),
    path('admin/', admin.site.urls),
    path('manage/', include('administrador.urls', namespace='manage'))
]

#FILEBROWSER_DIRECTORY = getattr(settings, 'FILEBROWSER_DIRECTORY', 'uploads/')

plantilla/administrador/models.py
from django.db import models

ACTIVO = (
	('si', 'si'),
	('no', 'no')
)

# Create your models here.
class Sliders(models.Model):
	titulo = models.CharField(max_length=255)
	image = models.ImageField()
	activo = models.CharField(max_length = 20, choices = ACTIVO)
	created_at = models.DateTimeField(auto_now_add=True)
	update_at = models.DateTimeField(auto_now=True)

	def __str__(self):
		return self.titulo

class Contenidos(models.Model):
	titulo = models.CharField(max_length=255)
	texto = models.TextField()
	activo = models.CharField(max_length = 20, choices = ACTIVO)
	orden = models.IntegerField(default=0)
	created_at = models.DateTimeField(auto_now_add=True)
	update_at = models.DateTimeField(auto_now=True)		
		

plantilla/administrador/forms.py
from django import forms

class LoginForm(forms.Form):
	dateusername = forms.TextInput(attrs={
		'size': 10,
		'title': 'Nombre usuario',
		'class': 'form-control placeholder-no-fix',
		'id': 'username',
		'placeholder': 'Username',
		'autocomplete': 'off'
	})

	datepassword = forms.PasswordInput(attrs={
		'title': 'Nombre usuario',
		'class': 'form-control placeholder-no-fix',
		'id': 'password',
		'placeholder': 'Password',
		'autocomplete': 'off'
	})

	username = dateusername.render('username', '')
	password = datepassword.render('password', '')

plantilla/administrador/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, Http404, JsonResponse
from django.contrib.auth import authenticate, login
from django.views.generic import View, TemplateView
from django.core.files.storage import FileSystemStorage
from django.conf import settings

from administrador.models import Contenidos, Sliders

from administrador.forms import LoginForm
from plantilla.funciones import IsValidM, covert_object

import json
import os

# Create your views here.
class LoginAdmin(View):
	def get(self, request, *args, **kwargs):
		form = LoginForm(request.POST or None)
		print(form)
		return render(request, 'administrador/home.html', {'form': form})

def login_admin(request):
	if request.method == 'POST':
		validar = IsValidM(request.POST, 
			{
				'username': 'required|alpha_dash',
				'password': 'required'
			}
		)
		if validar.is_valid():
			user = authenticate(username=request.POST['username'], password=request.POST['password'])
			if not user:
				respuesta = {
					'code': 20,
					'boolean': False,
					'error': 'Datos incorrectos',
					'result': ''
				}
			elif user.is_superuser == 1:
				login(request, user)
				respuesta = {
					'code': 0,
					'boolean': True,
					'error': '',
					'result': ''
				}
			else:
				respuesta = {
					'code': 21,
					'boolean': False,
					'error': 'Datos incorrectos',
					'result': ''
				}
		else:
			respuesta = {
				'code': 10,
				'boolean': False,
				'error': validar.errors(),
				'result': ''
			}

		return JsonResponse(respuesta, safe=False)
	else:
		return redirect('home')

class HomeAdmin(View):
	def get(self, request,*args, **kwargs):
		if not request.user.is_authenticated:
			return redirect('/manage')
		else:
			return render(request, 'administrador/inicio.html')

class SlidersAdmin (View):
	def get(self, request, *args, **kwargs):
		if not request.user.is_authenticated:
			return redirect('/manage')
		else:
			imagenes = Sliders.objects.all()
			return render(request, 'administrador/sliders/home.html', {'imagenes': imagenes})

class NewEditViewSlider(View):
	def get(self, request, *args, **kwargs):
		if not request.user.is_authenticated:
			return redirect('/manage')

		actiontype = kwargs['actiontype']

		if 'id' in kwargs:
			idR = kwargs['id']
			datos = Sliders.objects.get(id=idR)
		else:
			idR = 0
			datos = None

		if actiontype == 'add':
			texto_action = 'nuevo'
		elif actiontype == 'edit':
			texto_action = 'editar'
		else:
			texto_action = ''

		return render(request, 'administrador/sliders/new_edit.html', {
			'id': idR,
			'actiontype': {
				'tipo': actiontype,
				'texto': texto_action
			},
			'slider': datos
		})

def post_add_edit(request):
	if request.method == 'POST':
		validar = IsValidM(request.POST, {
			'actiontype': 'required|alpha'
		})

		if not request.user.is_authenticated:
			respuesta = {
				'code': 5,
				'boolean': False,
				'error': 'Sesión caducada',
				'result': ''
			}
		elif not validar.is_valid():
			respuesta = {
				'code': 10,
				'boolean': False,
				'error': validar.errors(),
				'result': ''
			}
		else:
			if request.POST['actiontype'] == 'add':
				validar_datos = IsValidM(request.POST, {
					'titulo': 'required|alpha_spaces_num|max:200'
				})
				validar_image = IsValidM(request.FILES, {
					'imagen': 'required'
				})

				if not validar_datos.is_valid():
					respuesta = {
						'code': 10,
						'boolean': False,
						'error': validar.errors(),
						'result': ''
					}
				elif not validar_image.is_valid():
					respuesta = {
						'code': 10,
						'boolean': False,
						'error': validar.errors(),
						'result': ''
					}
				else:
					file = request.FILES['imagen']
					fs = FileSystemStorage()
					filename = fs.save(file.name, file)
					uploaded_file_url = fs.url(filename)

					slider = Sliders()
					slider.titulo = request.POST['titulo']
					slider.image = file
					slider.activo = 'si'
					slider.save()

					respuesta = {
						'code': 0,
						'boolean': True,
						'error': '',
						'result': 'datos guardados'
					}
			elif request.POST['actiontype'] == 'edit':
				validar_datos = IsValidM(request.POST, {
					'id': 'required|numeric',
					'titulo': 'required|alpha_spaces_num|max:200'
				})

				if not validar_datos.is_valid():
					respuesta = {
						'code': 10,
						'boolean': False,
						'error': validar_datos.errors(),
						'result': ''
					}
				else:
					slider = Sliders.objects.get(id=request.POST['id'])

					if request.FILES:
						file = request.FILES['imagen']
						fs = FileSystemStorage()
						filename = fs.save(file.name, file)
						uploaded_file_url = fs.url(filename)

						del_image_path = os.path.join(settings.MEDIA_ROOT, str(slider.image))
						try:
							os.unlink(del_image_path)
						except:
							print('ocurrio un error a eliminar el archivo')

						slider.image = file

					slider.titulo = request.POST['titulo']
					slider.activo = 'si'
					slider.save()

					respuesta = {
						'code': 0,
						'boolean': True,
						'error': '',
						'result': 'datos modificados'
					}

		return JsonResponse(respuesta, safe=False)
	else:
		return redirect('slider')
		
def post_delete_slider(request, *args, **kwargs):
	print(kwargs['id'])
	if request.method == 'POST':
		validar_datos = IsValidM({'id': kwargs['id']}, {
			'id': 'required|numeric'
		})

		if not validar_datos.is_valid():
			respuesta = {
				'code': 10,
				'boolean': False,
				'error': validar_datos.errors(),
				'result': ''
			}
		else:
			slider = Sliders.objects.get(id=kwargs['id'])

			del_image_path = os.path.join(settings.MEDIA_ROOT, str(slider.image))

			try:
				os.unlink(del_image_path)
			except:
				print('ocurrio un error a eliminar el archivo')

			Sliders.objects.filter(id=kwargs['id']).delete()
			respuesta = {
				'code': 0,
				'boolean': True,
				'error': '',
				'result': 'Datos eliminados'
			}
		return JsonResponse(respuesta, safe=False)
	else:
		return redirect('slider')

class ContenidosAdmin(View):
	def get(self, request, *args, **kwargs):
		if not request.user.is_authenticated:
			return redirect('/manage')
		else:
			contenidos = Contenidos.objects.all()
			return render(request, 'administrador/contenido/home.html', {'contenidos': contenidos})

class NewEditViewContenido(View):
	def get(self, request, *args, **kwargs):
		if not request.user.is_authenticated:
			return redirect('/manage')

		actiontype = kwargs['actiontype']

		if 'id' in kwargs:
			idR = kwargs['id']
			datos = Contenidos.objects.get(id=idR)
			acsi = 'checked' if datos.activo == 'si' else ''
			acno = 'checked' if datos.activo == 'no' else ''
		else:
			idR = 0
			datos = None
			acsi = ''
			acno = ''

		if actiontype == 'add':
			texto_action = 'nuevo'
		elif actiontype == 'edit':
			texto_action = 'editar'
		else:
			texto_action = ''

		return render(request, 'administrador/contenido/new_edit.html', {
			'id': idR,
			'actiontype': {
				'tipo': actiontype,
				'texto': texto_action
			},
			'contenido': datos,
			'activo': {
				'si': acsi,
				'no': acno
			}
		})

def post_add_edit_contenido(request):
	if request.method == 'POST':
		validar = IsValidM(request.POST, {
			'actiontype': 'required|alpha'
		})

		if not request.user.is_authenticated:
			respuesta = {
				'code': 5,
				'boolean': False,
				'error': 'Sesión caducada',
				'result': ''
			}
		elif not validar.is_valid():
			respuesta = {
				'code': 10,
				'boolean': False,
				'error': validar.errors(),
				'result': ''
			}
		else:
			if request.POST['actiontype'] == 'add':
				validar_datos = IsValidM(request.POST, {
					'titulo': 'required|alpha_spaces_num|max:200'
				})

				if not validar_datos.is_valid():
					respuesta = {
						'code': 10,
						'boolean': False,
						'error': validar.errors(),
						'result': ''
					}
				else:
					contenido_ult = Contenidos.objects.order_by('-id')[:1]

					print(len(contenido_ult))

					if len(contenido_ult) == 0:
						orden_num = 1
					else:
						orden_num = contenido_ult[0].orden + 1

					contenido = Contenidos()
					contenido.titulo = request.POST['titulo']
					contenido.texto = request.POST['texto']
					contenido.activo = request.POST['activo']
					contenido.orden = orden_num
					contenido.save()

					respuesta = {
						'code': 0,
						'boolean': True,
						'error': '',
						'result': 'datos guardados'
					}
			elif request.POST['actiontype'] == 'edit':
				validar_datosBc = IsValidM(request.POST, {
					'id': 'required|numeric',
					'titulo': 'required|alpha_spaces_num|max:200'
				})

				if not validar_datosBc.is_valid():
					respuesta = {
						'code': 10,
						'boolean': False,
						'error': validar.errors(),
						'result': '555'
					}
				else:
					contenido = Contenidos.objects.get(id=request.POST['id'])

					contenido.titulo = request.POST['titulo']
					contenido.texto = request.POST['texto']
					contenido.activo = request.POST['activo']
					contenido.save()

					respuesta = {
						'code': 0,
						'boolean': True,
						'error': '',
						'result': 'datos modificados'
					}

		return JsonResponse(respuesta, safe=False)
	else:
		return redirect('contenidos')

def post_delete_contenido(request, *args, **kwargs):
	if request.method == 'POST':
		validar_datos = IsValidM({'id': kwargs['id']}, {
			'id': 'required|numeric'
		})

		if not validar_datos.is_valid():
			respuesta = {
				'code': 10,
				'boolean': False,
				'error': validar_datos.errors(),
				'result': ''
			}
		else:
			Contenidos.objects.filter(id=kwargs['id']).delete()
			respuesta = {
				'code': 0,
				'boolean': True,
				'error': '',
				'result': 'Datos eliminados'
			}
		return JsonResponse(respuesta, safe=False)
	else:
		return redirect('slider')

plantilla/administrador/templates/administrador/home.html
{% load staticfiles %}
<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html lang="es">
<head>
	<meta charset="utf-8" />
	<title>Administrador</title>
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />
	<meta content="width=device-width, initial-scale=1.0" name="viewport" />
	<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
	<meta content="" name="login admin" />
	<link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all" rel="stylesheet" type="text/css"/>
	<link href="{% static 'css/bootstrap/bootstrap.min.css' %}" rel="stylesheet" type="text/css"/>
	<link href="{% static 'css/fontawesome.css' %}" rel="stylesheet" type="text/css"/>
	<link href="{% static 'css/simple-line-icons.css' %}" rel="stylesheet" type="text/css"/>
	<link rel="stylesheet" href="{% static 'css/sweetalert2.min.css' %}" />
	<link rel="stylesheet" href="{% static 'css/app.css' %}" />
	<link rel="shortcut icon" href="favicon.ico"/>
</head>
<body class="container-fluid login">
	<!-- LOADER -->
	<aside class="loading-adming">
		<div class="modalLoaderCont">
			<div id="loading">
				<div class="loader--dot"></div>
				<div class="loader--dot"></div>
				<div class="loader--dot"></div>
				<div class="loader--dot"></div>
				<div class="loader--dot"></div>
				<div class="loader--dot"></div>
				<div class="loader--text"></div>
			</div>
		</div>
	</aside>
	<!-- END LOADER -->
	<aside class="row align-items-center justify-content-center recordar-pass">
		<form id="emailpass" class="formpass" method="post" action="#">
			{% csrf_token %}
			<div class="form-group">
				<label class="control-label visible-ie8 visible-ie9">Email</label>
				<div class="input-icon">
					<i class="fa fa-user iconManageLogin"></i>
					<input class="form-control placeholder-no-fix" type="email" autocomplete="off" placeholder="Email" name="email" id="email" />
				</div>
			</div>
			<div class="row justify-content-center form-actions">
				<button type="submit" class="btn btn-primary btn-lg btnrecordar">
					Enviar <i class="m-icon-swapright m-icon-white"></i>
				</button>
				<a href="#" class="btn btn-secondary btn-lg btncancelpass">
					Cancelar <i class="m-icon-swapright m-icon-white"></i>
				</a>
			</div>
		</form>
	</aside>
	<section class="row content">
		<div class="col-md col-xs-12"></div>
		<div class="col-md col-xs-12">
			<form id="login" class="formlogin" action="{% url 'manage:login' %}" method="post">
				<div class="row align-items-center justify-content-center caja-form">
					<div class="col-md-8 col-xs-12 mainLoginForm">
						<div class="logo">
							<figure>
								<a href="#">
									<img src="{% static 'images/logo.png' %}" alt="logo" />
								</a>
							</figure>
						</div>
						{% csrf_token %}
						<h3 class="form-title">Ingrese a su cuenta</h3>
						<div class="alert alert-danger display-hide display-none">
							<button class="close" data-close="alert"></button>
							<span>
							Ingrese nombre de usuario y contraseña. </span>
						</div>
						<div class="form-group">
							<label class="control-label visible-ie8 visible-ie9">Usuario</label>
							<div class="input-icon">
								<i class="fa fa-user iconManageLogin"></i>
								{{form.username}}
							</div>
						</div>
						<div class="form-group">
							<label class="control-label visible-ie8 visible-ie9">Contraseña</label>
							<div class="input-icon">
								<i class="fa fa-lock iconManageLogin"></i>
								{{form.password}}
							</div>
						</div>
						<div class="forget-password">
							<h4>
								<a href="#" id="forget-password">Olvidaste tu contraseña ?</a>
							</h4>
						</div>
						<div class="form-actions flex flex-center">
							<button type="submit" class="btn btn-primary btn-lg btnLogin">
								Iniciar <i class="m-icon-swapright m-icon-white"></i>
							</button>
						</div>
					</div>
				</div>
			</form>
		</div>
	</section>
	<script src="{% static 'js/lib/jquery.min.js' %}"></script>
	<script src="{% static 'js/lib/jquery.backstretch.min.js' %}"></script>
	<script src="{% static 'js/lib/jquery.form.js' %}"></script>
	<script src="{% static 'js/lib/sweetalert2.min.js' %}"></script>
	<script src="{% static 'js/utils.js' %}"></script>
	<script src="{% static 'js/main.js' %}"></script>
	<script src="{% static 'js/admin_login.js' %}"></script>
	<script type="text/javascript">
		$(inicio_fondos);
		function inicio_fondos () {
			$.backstretch([
				"{% static 'images/1.jpg' %}",
				"{% static 'images/2.jpg' %}",
				"{% static 'images/3.jpg' %}",
				"{% static 'images/4.jpg' %}"
				], {
					fade: 1000,
					duration: 8000
				}
			);
		}
	</script>
</body>
</html>

plantilla/administrador/templates/administrador/inicio.html
{% extends "administrador/layout.html" %}
{% load staticfiles %}
{% block title %}Home{% endblock title %}

{% block selmenuadmin %}active{% endblock selmenuadmin %}

{% block content %}
	<section class="container-fluid">
    <div class="row">
      <div class="col-sm-6 col-lg-3">
        <div class="card">
          <div class="card-body">
            <div class="h4 m-0">
              2
            </div>
            <div>
              pdfs
            </div>
            <div class="progress progress-xs my-3">
              <div class="progress-bar" role="progressbar" style="width: 25%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
            </div>
          </div> 
        </div> 
      </div> 
    </div> 
  </section>
{% endblock content %}

plantilla/administrador/templates/administrador/layout.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />
	<meta name="description" content="Admin Template" />
	<link rel="apple-touch-icon" sizes="57x57" href="/favicon/apple-icon-57x57.png">
	<link rel="apple-touch-icon" sizes="60x60" href="/favicon/apple-icon-60x60.png">
	<link rel="apple-touch-icon" sizes="72x72" href="/favicon/apple-icon-72x72.png">
	<link rel="apple-touch-icon" sizes="76x76" href="/favicon/apple-icon-76x76.png">
	<link rel="apple-touch-icon" sizes="114x114" href="/favicon/apple-icon-114x114.png">
	<link rel="apple-touch-icon" sizes="120x120" href="/favicon/apple-icon-120x120.png">
	<link rel="apple-touch-icon" sizes="144x144" href="/favicon/apple-icon-144x144.png">
	<link rel="apple-touch-icon" sizes="152x152" href="/favicon/apple-icon-152x152.png">
	<link rel="apple-touch-icon" sizes="180x180" href="/favicon/apple-icon-180x180.png">
	<link rel="icon" type="image/png" sizes="192x192"  href="/favicon/android-icon-192x192.png">
	<link rel="icon" type="image/png" sizes="32x32" href="/favicon/favicon-32x32.png">
	<link rel="icon" type="image/png" sizes="96x96" href="/favicon/favicon-96x96.png">
	<link rel="icon" type="image/png" sizes="16x16" href="/favicon/favicon-16x16.png">
	<link rel="manifest" href="/favicon/manifest.json">
	<meta name="msapplication-TileColor" content="#ffffff">
	<meta name="msapplication-TileImage" content="/favicon/ms-icon-144x144.png">
	<meta name="theme-color" content="#ffffff">
	<title>{% block title %}Administrador{% endblock %}</title>
	<link type="text/css" rel="stylesheet" href="{% static 'css/fontawesome.css' %}" />
	{% block cssplugins %}{% endblock %}
	<link type="text/css" rel="stylesheet" href="{% static 'css/sweetalert2.min.css' %}" />
	<link type="text/css" rel="stylesheet" href="{% static 'js/lib/datatables/dataTables.bootstrap4.min.css' %}" />
	<link type="text/css" rel="stylesheet" href="{% static 'js/lib/datatables/FixedHeader/css/fixedHeader.bootstrap.min.css' %}" />
	<link type="text/css" rel="stylesheet" href="{% static 'js/lib/datatables/Responsive/css/responsive.bootstrap.min.css' %}" />
	<link rel="stylesheet" href="{% static 'css/app.css' %}" />
	{% block css %}{% endblock %}
</head>
<body class="app header-fixed sidebar-fixed aside-menu-fixed aside-menu-hidden">
	<!-- LOADER -->
	<aside class="loading-adming">
		<div class="modalLoaderCont">
			<div id="loading">
				<div class="loader--dot"></div>
				<div class="loader--dot"></div>
				<div class="loader--dot"></div>
				<div class="loader--dot"></div>
				<div class="loader--dot"></div>
				<div class="loader--dot"></div>
				<div class="loader--text"></div>
			</div>
		</div>
	</aside>
	<!-- END LOADER -->
	{% include 'administrador/includes/header.html' %}
	<section class="app-body">
		{% include 'administrador/includes/menuvertical.html' %}
		<section class="main">
			{% block content %}{% endblock %}
		</section>
	</section>
	{% include 'administrador/includes/footer.html' %}
	<script src="{% static 'js/lib/jquery.min.js' %}"></script>
	<script src="{% static 'js/lib/popper.min.js' %}"></script>
	<script src="{% static 'js/lib/bootstrap.min.js' %}"></script>
	<script src="{% static 'js/lib/datatables/datatables.min.js' %}"></script>
	<script src="{% static 'js/lib/datatables/dataTables.bootstrap4.min.js' %}"></script>
	<script src="{% static 'js/lib/datatables/Responsive/js/dataTables.responsive.min.js' %}"></script>
	<script src="{% static 'js/lib/pace.min.js' %}"></script>
	<script src="{% static 'js/lib/sweetalert2.min.js' %}"></script>
	<script src="{% static 'js/lib/Chart.min.js' %}"></script>
	<script src="{% static 'js/plantilla.js' %}"></script>
	<script src="{% static 'js/utils.js' %}"></script>
	<script src="{% static 'js/main.js' %}"></script>
	{% block js %}{% endblock %}
</body>
</html>