plantilla/administrador/urls.py
from django.urls import path, re_path
from django.contrib.auth.views import logout
from administrador.views import (
	LoginAdmin,
	login_admin,
	HomeAdmin,
	SlidersAdmin,
	NewEditViewSlider,
	post_add_edit,
	post_delete_slider,
	ContenidosAdmin,
	NewEditViewContenido,
	post_add_edit_contenido,
	post_delete_contenido
)

app_name = 'manage'

urlpatterns = [
	path('', LoginAdmin.as_view(), name = 'home'),
	path('login', login_admin, name = 'login'),
	path('logout/', logout, {'next_page': '/manage'}, name='logout'),
	path('home/', HomeAdmin.as_view(), name = 'homeadmin'),
	path('slider/', SlidersAdmin.as_view(), name = 'slider'),
	path('slidernewedit/<actiontype>/', NewEditViewSlider.as_view(), name = 'addeditslider'),
	path('slidernewedit/<actiontype>/<id>/', NewEditViewSlider.as_view(), name = 'addeditslider'),
	path('newslider/', post_add_edit, name = 'postnewslider'),
	path('editslider/', post_add_edit, name = 'posteditslider'),
	path('deleteslider/<id>', post_delete_slider, name = 'postdeleteslider'),
	path('contenidos/', ContenidosAdmin.as_view(), name = 'contenidos'),
	path('contenidonewedit/<actiontype>/', NewEditViewContenido.as_view(), name = 'addeditcontenido'),
	path('contenidonewedit/<actiontype>/<id>/', NewEditViewContenido.as_view(), name = 'addeditcontenido'),
	path('newcontenido/', post_add_edit_contenido, name = 'postnewcontenido'),
	path('editcontenido/', post_add_edit_contenido, name = 'posteditcontenido'),
	path('deletecontenido/<id>', post_delete_contenido, name = 'postdeletecontenido')
]

plantilla/plantilla/urls.py
from django.contrib import admin
from filebrowser.sites import site
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
	path('admin-manage/filebrowser/', site.urls),
    path('admin/', admin.site.urls),
    path('manage/', include('administrador.urls', namespace='manage'))
]

#FILEBROWSER_DIRECTORY = getattr(settings, 'FILEBROWSER_DIRECTORY', 'uploads/')

plantilla/administrador/models.py
from django.db import models

ACTIVO = (
	('si', 'si'),
	('no', 'no')
)

# Create your models here.
class Sliders(models.Model):
	titulo = models.CharField(max_length=255)
	image = models.ImageField()
	activo = models.CharField(max_length = 20, choices = ACTIVO)
	created_at = models.DateTimeField(auto_now_add=True)
	update_at = models.DateTimeField(auto_now=True)

	def __str__(self):
		return self.titulo

class Contenidos(models.Model):
	titulo = models.CharField(max_length=255)
	texto = models.TextField()
	activo = models.CharField(max_length = 20, choices = ACTIVO)
	orden = models.IntegerField(default=0)
	created_at = models.DateTimeField(auto_now_add=True)
	update_at = models.DateTimeField(auto_now=True)		
		

plantilla/administrador/forms.py
from django import forms

class LoginForm(forms.Form):
	dateusername = forms.TextInput(attrs={
		'size': 10,
		'title': 'Nombre usuario',
		'class': 'form-control placeholder-no-fix',
		'id': 'username',
		'placeholder': 'Username',
		'autocomplete': 'off'
	})

	datepassword = forms.PasswordInput(attrs={
		'title': 'Nombre usuario',
		'class': 'form-control placeholder-no-fix',
		'id': 'password',
		'placeholder': 'Password',
		'autocomplete': 'off'
	})

	username = dateusername.render('username', '')
	password = datepassword.render('password', '')

plantilla/administrador/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, Http404, JsonResponse
from django.contrib.auth import authenticate, login
from django.views.generic import View, TemplateView
from django.core.files.storage import FileSystemStorage
from django.conf import settings

from administrador.models import Contenidos, Sliders

from administrador.forms import LoginForm
from plantilla.funciones import IsValidM, covert_object

import json
import os

# Create your views here.
class LoginAdmin(View):
	def get(self, request, *args, **kwargs):
		form = LoginForm(request.POST or None)
		print(form)
		return render(request, 'administrador/home.html', {'form': form})

def login_admin(request):
	if request.method == 'POST':
		validar = IsValidM(request.POST, 
			{
				'username': 'required|alpha_dash',
				'password': 'required'
			}
		)
		if validar.is_valid():
			user = authenticate(username=request.POST['username'], password=request.POST['password'])
			if not user:
				respuesta = {
					'code': 20,
					'boolean': False,
					'error': 'Datos incorrectos',
					'result': ''
				}
			elif user.is_superuser == 1:
				login(request, user)
				respuesta = {
					'code': 0,
					'boolean': True,
					'error': '',
					'result': ''
				}
			else:
				respuesta = {
					'code': 21,
					'boolean': False,
					'error': 'Datos incorrectos',
					'result': ''
				}
		else:
			respuesta = {
				'code': 10,
				'boolean': False,
				'error': validar.errors(),
				'result': ''
			}

		return JsonResponse(respuesta, safe=False)
	else:
		return redirect('home')

class HomeAdmin(View):
	def get(self, request,*args, **kwargs):
		if not request.user.is_authenticated:
			return redirect('/manage')
		else:
			return render(request, 'administrador/inicio.html')

class SlidersAdmin (View):
	def get(self, request, *args, **kwargs):
		if not request.user.is_authenticated:
			return redirect('/manage')
		else:
			imagenes = Sliders.objects.all()
			return render(request, 'administrador/sliders/home.html', {'imagenes': imagenes})

class NewEditViewSlider(View):
	def get(self, request, *args, **kwargs):
		if not request.user.is_authenticated:
			return redirect('/manage')

		actiontype = kwargs['actiontype']

		if 'id' in kwargs:
			idR = kwargs['id']
			datos = Sliders.objects.get(id=idR)
		else:
			idR = 0
			datos = None

		if actiontype == 'add':
			texto_action = 'nuevo'
		elif actiontype == 'edit':
			texto_action = 'editar'
		else:
			texto_action = ''

		return render(request, 'administrador/sliders/new_edit.html', {
			'id': idR,
			'actiontype': {
				'tipo': actiontype,
				'texto': texto_action
			},
			'slider': datos
		})

def post_add_edit(request):
	if request.method == 'POST':
		validar = IsValidM(request.POST, {
			'actiontype': 'required|alpha'
		})

		if not request.user.is_authenticated:
			respuesta = {
				'code': 5,
				'boolean': False,
				'error': 'Sesión caducada',
				'result': ''
			}
		elif not validar.is_valid():
			respuesta = {
				'code': 10,
				'boolean': False,
				'error': validar.errors(),
				'result': ''
			}
		else:
			if request.POST['actiontype'] == 'add':
				validar_datos = IsValidM(request.POST, {
					'titulo': 'required|alpha_spaces_num|max:200'
				})
				validar_image = IsValidM(request.FILES, {
					'imagen': 'required'
				})

				if not validar_datos.is_valid():
					respuesta = {
						'code': 10,
						'boolean': False,
						'error': validar.errors(),
						'result': ''
					}
				elif not validar_image.is_valid():
					respuesta = {
						'code': 10,
						'boolean': False,
						'error': validar.errors(),
						'result': ''
					}
				else:
					file = request.FILES['imagen']
					fs = FileSystemStorage()
					filename = fs.save(file.name, file)
					uploaded_file_url = fs.url(filename)

					slider = Sliders()
					slider.titulo = request.POST['titulo']
					slider.image = file
					slider.activo = 'si'
					slider.save()

					respuesta = {
						'code': 0,
						'boolean': True,
						'error': '',
						'result': 'datos guardados'
					}
			elif request.POST['actiontype'] == 'edit':
				validar_datos = IsValidM(request.POST, {
					'id': 'required|numeric',
					'titulo': 'required|alpha_spaces_num|max:200'
				})

				if not validar_datos.is_valid():
					respuesta = {
						'code': 10,
						'boolean': False,
						'error': validar_datos.errors(),
						'result': ''
					}
				else:
					slider = Sliders.objects.get(id=request.POST['id'])

					if request.FILES:
						file = request.FILES['imagen']
						fs = FileSystemStorage()
						filename = fs.save(file.name, file)
						uploaded_file_url = fs.url(filename)

						del_image_path = os.path.join(settings.MEDIA_ROOT, str(slider.image))
						try:
							os.unlink(del_image_path)
						except:
							print('ocurrio un error a eliminar el archivo')

						slider.image = file

					slider.titulo = request.POST['titulo']
					slider.activo = 'si'
					slider.save()

					respuesta = {
						'code': 0,
						'boolean': True,
						'error': '',
						'result': 'datos modificados'
					}

		return JsonResponse(respuesta, safe=False)
	else:
		return redirect('slider')
		
def post_delete_slider(request, *args, **kwargs):
	print(kwargs['id'])
	if request.method == 'POST':
		validar_datos = IsValidM({'id': kwargs['id']}, {
			'id': 'required|numeric'
		})

		if not validar_datos.is_valid():
			respuesta = {
				'code': 10,
				'boolean': False,
				'error': validar_datos.errors(),
				'result': ''
			}
		else:
			slider = Sliders.objects.get(id=kwargs['id'])

			del_image_path = os.path.join(settings.MEDIA_ROOT, str(slider.image))

			try:
				os.unlink(del_image_path)
			except:
				print('ocurrio un error a eliminar el archivo')

			Sliders.objects.filter(id=kwargs['id']).delete()
			respuesta = {
				'code': 0,
				'boolean': True,
				'error': '',
				'result': 'Datos eliminados'
			}
		return JsonResponse(respuesta, safe=False)
	else:
		return redirect('slider')

class ContenidosAdmin(View):
	def get(self, request, *args, **kwargs):
		if not request.user.is_authenticated:
			return redirect('/manage')
		else:
			contenidos = Contenidos.objects.all()
			return render(request, 'administrador/contenido/home.html', {'contenidos': contenidos})

class NewEditViewContenido(View):
	def get(self, request, *args, **kwargs):
		if not request.user.is_authenticated:
			return redirect('/manage')

		actiontype = kwargs['actiontype']

		if 'id' in kwargs:
			idR = kwargs['id']
			datos = Contenidos.objects.get(id=idR)
			acsi = 'checked' if datos.activo == 'si' else ''
			acno = 'checked' if datos.activo == 'no' else ''
		else:
			idR = 0
			datos = None
			acsi = ''
			acno = ''

		if actiontype == 'add':
			texto_action = 'nuevo'
		elif actiontype == 'edit':
			texto_action = 'editar'
		else:
			texto_action = ''

		return render(request, 'administrador/contenido/new_edit.html', {
			'id': idR,
			'actiontype': {
				'tipo': actiontype,
				'texto': texto_action
			},
			'contenido': datos,
			'activo': {
				'si': acsi,
				'no': acno
			}
		})

def post_add_edit_contenido(request):
	if request.method == 'POST':
		validar = IsValidM(request.POST, {
			'actiontype': 'required|alpha'
		})

		if not request.user.is_authenticated:
			respuesta = {
				'code': 5,
				'boolean': False,
				'error': 'Sesión caducada',
				'result': ''
			}
		elif not validar.is_valid():
			respuesta = {
				'code': 10,
				'boolean': False,
				'error': validar.errors(),
				'result': ''
			}
		else:
			if request.POST['actiontype'] == 'add':
				validar_datos = IsValidM(request.POST, {
					'titulo': 'required|alpha_spaces_num|max:200'
				})

				if not validar_datos.is_valid():
					respuesta = {
						'code': 10,
						'boolean': False,
						'error': validar.errors(),
						'result': ''
					}
				else:
					contenido_ult = Contenidos.objects.order_by('-id')[:1]

					print(len(contenido_ult))

					if len(contenido_ult) == 0:
						orden_num = 1
					else:
						orden_num = contenido_ult[0].orden + 1

					contenido = Contenidos()
					contenido.titulo = request.POST['titulo']
					contenido.texto = request.POST['texto']
					contenido.activo = request.POST['activo']
					contenido.orden = orden_num
					contenido.save()

					respuesta = {
						'code': 0,
						'boolean': True,
						'error': '',
						'result': 'datos guardados'
					}
			elif request.POST['actiontype'] == 'edit':
				validar_datosBc = IsValidM(request.POST, {
					'id': 'required|numeric',
					'titulo': 'required|alpha_spaces_num|max:200'
				})

				if not validar_datosBc.is_valid():
					respuesta = {
						'code': 10,
						'boolean': False,
						'error': validar.errors(),
						'result': '555'
					}
				else:
					contenido = Contenidos.objects.get(id=request.POST['id'])

					contenido.titulo = request.POST['titulo']
					contenido.texto = request.POST['texto']
					contenido.activo = request.POST['activo']
					contenido.save()

					respuesta = {
						'code': 0,
						'boolean': True,
						'error': '',
						'result': 'datos modificados'
					}

		return JsonResponse(respuesta, safe=False)
	else:
		return redirect('contenidos')

def post_delete_contenido(request, *args, **kwargs):
	if request.method == 'POST':
		validar_datos = IsValidM({'id': kwargs['id']}, {
			'id': 'required|numeric'
		})

		if not validar_datos.is_valid():
			respuesta = {
				'code': 10,
				'boolean': False,
				'error': validar_datos.errors(),
				'result': ''
			}
		else:
			Contenidos.objects.filter(id=kwargs['id']).delete()
			respuesta = {
				'code': 0,
				'boolean': True,
				'error': '',
				'result': 'Datos eliminados'
			}
		return JsonResponse(respuesta, safe=False)
	else:
		return redirect('slider')

plantilla/administrador/templates/administrador/sliders/home.html
{% extends "administrador/layout.html" %}
{% load staticfiles %}
{% block title %}Slider Imágenes{% endblock title %}

{% block selmenuslider %}active{% endblock selmenuslider %}

{% block content %}
<!-- BEGIN CONTENT -->
<div class="container-fluid">
	<div class="animated fadeIn">
		<div class="row">
			<div class="col-lg-12">
				<div class="card ">
					<div class="card-header">
						<div class="row">
							<div class="col-md-10"><h3>Sliders</h3></div>
							<div class="col-md-2 text-right"><a href="/manage/slidernewedit/add" class="btn btn-primary addItemBtn">Agregar nuevo</a></div>
						</div>
					</div>
					<div class="card-body">
						<div id="tokendiv">
							{% csrf_token %}
						</div>
						<table id="data-table" class="table table-striped table-bordered" cellspacing="0" width="100%">
							<thead>
								<tr>
									<th>
										ID
									</th>
									<th>
										Titulo
									</th>
									<th>
										Imagen
									</th>
									<th>
										Acciones	
									</th>
								</tr>
							</thead>
							<tbody>
								{% for slider in imagenes %}
								<tr id="fila-anime{{slider.id}}">
									<td>
										<div>
											<span>{{slider.id}}</span>
										</div>
									</td>
									<td>
										<div>
											<span>{{slider.titulo}}</span>
										</div>
									</td>
									<td>
										<center>
											<figure class="miniatura" style="background-image: url({% static 'assets/images/' %}{{slider.image}});"></figure>
										</center>
									</td>
									<td>
										<div>
											<a href="/manage/slidernewedit/edit/{{slider.id}}" class="btn btn-primary"><i class="fa fa-cogs"></i> Modificar</a>
											<a href="/manage/deleteslider/{{slider.id}}" class="btn btn-danger delete-datos" data-id="{{slider.id}}"><i class="fa fa-remove"></i> Borrar</a>
										</div>
									</td>
								</tr>
								{% endfor %}
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- END CONTENT -->
{% endblock content %}
{% block js %}
	<script src="{% static 'js/lib/jquery.form.js' %}"></script>
	<script src="{% static 'js/slider_admin.js' %}"></script>
{% endblock js %}

plantilla/administrador/templates/administrador/sliders/new_edit.html
{% extends "administrador/layout.html" %}
{% load staticfiles %}
{% block title %}Slider Imágenes{% endblock title %}

{% block selmenuslider %}active{% endblock selmenuslider %}

{% block content %}
<!-- BEGIN CONTENT -->
<div class="container-fluid">
	<div class="animated fadeIn">
		<div class="row">
			<div class="col-lg-12">
				<div class="card ">
					<div class="card-header">
						<div class="row">
							<div class="col-md-10"><h3>Sliders <small>{{actiontype.texto}}</small></h3></div>
						</div>
					</div>
					<div class="card-body">
						{% if actiontype.tipo == 'add' %}
							<form id="sliderForm" action="{% url 'manage:postnewslider' %}" method="post" enctype="multipart/form-data">
								{% csrf_token %}
								<input type="hidden" id="actiontype" name="actiontype" value="{{actiontype.tipo}}" />
								<div class="form-group">
									<label class="control-label">Titulo</label>
									<input type="text" id="titulo" name="titulo" class="form-control no-padding-control" placeholder="Titulo de slider">
								</div>
								<div class="form-group">
									<label class="control-label">Selecione la imagen</label><br>
									<input type="file" name="imagen" id="imagen">
								</div>
								<div class="form-actions right">
									<a href="{% url 'manage:slider' %}" class="btn default">Cancelar</a>
									<button id="enviar" class="btn blue"><i class="fa fa-check"></i> Guardar</button>
								</div>
							</form>
						{% elif actiontype.tipo == 'edit' %}
							<form id="sliderForm" action="{% url 'manage:posteditslider' %}" method="post" enctype="multipart/form-data">
								{% csrf_token %}
								<input type="hidden" name="id" id="id" value="{{slider.id}}">
								<input type="hidden" id="actiontype" name="actiontype" value="{{actiontype.tipo}}" />
								<div class="form-group">
									<label class="control-label">Titulo</label>
									<input type="text" id="titulo" name="titulo" class="form-control no-padding-control no-padding-control" placeholder="Titulo de slider" value="{{slider.titulo}}">
								</div>
								<figure class="fileinput-new thumbnail" style="width: 200px;">
									<img src="{% static 'assets/images/' %}{{slider.image}}" />
								</figure>
								<div class="form-group">
									<label class="control-label">Selecione la imagen</label>
									<input type="file" name="imagen" id="imagen">
								</div>
								<div class="form-actions right">
									<a href="{% url 'manage:slider' %}" class="btn default">Cancelar</a>
									<button id="enviar" class="btn blue"><i class="fa fa-check"></i> Guardar</button>
								</div>
							</form>
						{% endif %}
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- END CONTENT -->
{% endblock content %}
{% block js %}
	<script src="{% static 'js/lib/jquery.form.js' %}"></script>
	<script src="{% static 'js/slider_admin.js' %}"></script>
{% endblock js %}